export const posts = [
    {
        id: 0,
        title: "Nintendo Finally Announces Tomodachi Life 2",
        url: "https://static1.srcdn.com/wordpress/wp-content/uploads/2025/03/a-giant-mii-looming-over-another-much-smaller-mii-in-the-tomodachi-life-living-the-dream-trailer.jpg",
        text: "Today's Nintendo Direct ended in a surprising and rather strange way, with the announcement of a brand new Tomodachi Life game after over a decade-long hiatus for the series. It's called Tomodachi Life: Living the Dream and it's not coming out until 2026. The original Tomodachi Life was first released back in 2013 in Japan and 2014 overseas, and is a social sim game featuring Nintendo's Mii characters. Both in the original and now in Living the Dream, the Miis live in a small community together, and players are able to have Miis with different personalities and stats interact with one another. Over time, the Miis can form different kinds of relationships with one another, and watch their lives evolve through different activities. Miis can even get married and have kids."
    },
    {
        id: 1,
        title: "Scientists Manage to Freeze Light in Quantum Breakthrough",
        url: "https://media.ahmedabadmirror.com/am/uploads/mediaGallery/image/1742153447501.jpg-org",
        text: "Scientists have succeeded in making light behave like a \"supersolid\" for the first time—a breakthrough that could improve our understanding of this exotic phase of matter. A supersolid has an ordered structure like a solid but can also flow without friction like a superfluid, and previously they have only been produced in so-called \"Bose-Einstein condensates\"—which are formed when a gas of atoms is cooled to near absolute zero. \"This is only the beginning of understanding supersolidity,\" said Italy-based physicists Antonio Gianfate of CNR Nanotec and Davide Nigro of the University of Pavia in a research summary."
    },
    {
        id: 2,
        title: "Device Enables Direct Communication Among Multiple Quantum Processors",
        url: "https://news.mit.edu/sites/default/files/styles/news_article__image_gallery/public/images/202503/MIT-Chiral-Interconnect-01-PRESS_0.jpg?itok=COsYwAin",
        text: "Quantum computers have the potential to solve complex problems that would be impossible for the most powerful classical supercomputer to crack. Just like a classical computer has separate, yet interconnected, components that must work together, such as a memory chip and a CPU on a motherboard, a quantum computer will need to communicate quantum information between multiple processors. Current architectures used to interconnect superconducting quantum processors are “point-to-point” in connectivity, meaning they require a series of transfers between network nodes, with compounding error rates."
    },
    {
        id: 3,
        title: "Students Develop Application to Guarantee Remote Data Access",
        url: "/src/assets/molenium.jpeg",
        text: "A shared problem in resource-constrained institutions is having secure remote access to data generated by scientific instrumentation whenever an emergency occurs, such as natural disasters, pandemics, and in the case of Puerto Rico, faults in critical infrastructure. In this work, we, Sebastián Ramírez and Gabriel Romero, present a web-based software system called Molenium to provide secure access to the data generated by scientific instrumentation. The system securely synchronizes the data generated by the instruments with a remote server accessible from anywhere through a web interface. We will discuss how we automate the configuration of the scientific instruments to synchronize with the server securely and how the data is presented to the users with different access levels."
    }
];